In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.gaussian_process import GaussianProcessRegressor

# Guide and Ideas for Capstone Project

We begin this guide by downloading the data:

In [2]:
X = np.load(r'C:\Users\cjorq\Downloads\initial_data/function_2/initial_inputs.npy')
Y = np.load(r'C:\Users\cjorq\Downloads\initial_data/function_2/initial_outputs.npy')

In [3]:
X

array([[0.66579958, 0.12396913],
       [0.87779099, 0.7786275 ],
       [0.14269907, 0.34900513],
       [0.84527543, 0.71112027],
       [0.45464714, 0.29045518],
       [0.57771284, 0.77197318],
       [0.43816606, 0.68501826],
       [0.34174959, 0.02869772],
       [0.33864816, 0.21386725],
       [0.70263656, 0.9265642 ]])

In [4]:
Y

array([ 0.53899612,  0.42058624, -0.06562362,  0.29399291,  0.21496451,
        0.02310555,  0.24461934,  0.03874902, -0.01385762,  0.61120522])

## Random Search

The simplest solution would be a simple random search, that is, we can randomly choose our next query point:

In [5]:
next_query = np.random.uniform(size=2)
formatted_query = '-'.join([f'{x:.6f}' for x in next_query])
print(formatted_query)

0.410637-0.267800


# Upper Confidence Bound

A second alternative would be to use Bayesian Optimization and consider an Upper Confidence Bound acquisition function: 

In [7]:
gpr = GaussianProcessRegressor()
gpr.fit(X, Y)

GaussianProcessRegressor()

In [8]:
# to optimize the acquisition function, we will simply use gridsearch over a space of 10.000 gridpoints
x1 = np.linspace(0, 1, 100)
x2 = np.linspace(0, 1, 100)

In [9]:
x2

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [10]:
X_grid = []
for i in range(len(x1)):
    for j in range(len(x2)):
        X_grid.append([x1[i], x2[j]])

In [11]:
len(X_grid)

10000

In [12]:
X_grid = np.array(X_grid)
mean, std = gpr.predict(X_grid, return_std = True)
ucb = mean + 1.96 * std

In [13]:
ucb

array([-1.62941594, -1.62551654, -1.6187959 , ...,  1.85291018,
        1.93755015,  2.02704494])

In [14]:
mean

array([-1.71134082, -1.70480819, -1.69548552, ...,  1.82998124,
        1.91299143,  2.00075276])

In [15]:
mean + std * 1.96

array([-1.62941594, -1.62551654, -1.6187959 , ...,  1.85291018,
        1.93755015,  2.02704494])

In [16]:
ucb

array([-1.62941594, -1.62551654, -1.6187959 , ...,  1.85291018,
        1.93755015,  2.02704494])

In [16]:
idx_max = np.argmax(ucb)
next_query = X_grid[idx_max]
print(next_query)

[0. 1.]
